spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_cache?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.eru.cache.mapper: debug
debug: true
